name: Erlang CI

on:
  push:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        otpvsn: [19, 20, 21, 22, 23]

    container:
      image: erlang:${{ matrix.otpvsn }}

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 do eunit
